/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Administrador;
import clases.Helper;
import clases.Mesero;
import static interfaz.Principal.cmdMesa1;
import static interfaz.Principal.cmdMesa10;
import static interfaz.Principal.cmdMesa2;
import static interfaz.Principal.cmdMesa3;
import static interfaz.Principal.cmdMesa4;
import static interfaz.Principal.cmdMesa5;
import static interfaz.Principal.cmdMesa6;
import static interfaz.Principal.cmdMesa7;
import static interfaz.Principal.cmdMesa8;
import static interfaz.Principal.cmdMesa9;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author hp 14
 */
public class Login_Mesero extends javax.swing.JDialog {

    /**
     * Creates new form Agregar_Admin
     */
    String rutaM, rutaA;
    ObjectOutputStream salida;

    public Login_Mesero(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rutaM = "src/datos/Mesero.txt";
        rutaA = "src/datos/Admin.txt";
        Helper.llenarComboNombresMeseros(cmbNombre, rutaM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cmbNombre = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        cmdOk = new javax.swing.JButton();
        cmdNuevo = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ADMINISTRADOR");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbCodigo.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jlbCodigo.setText("Codigo :");
        jPanel1.add(jlbCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 120, -1));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Nombre :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmbNombre.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        jPanel1.add(cmbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 240, 100));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdOk.setBackground(new java.awt.Color(0, 0, 0));
        cmdOk.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdOk.setForeground(new java.awt.Color(255, 255, 255));
        cmdOk.setText("Ok");
        cmdOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdOkActionPerformed(evt);
            }
        });
        jPanel2.add(cmdOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        cmdNuevo.setBackground(new java.awt.Color(0, 0, 0));
        cmdNuevo.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdNuevo.setForeground(new java.awt.Color(255, 255, 255));
        cmdNuevo.setText("Nuevo");
        cmdNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdNuevoActionPerformed(evt);
            }
        });
        jPanel2.add(cmdNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        cmdSalir.setBackground(new java.awt.Color(0, 0, 0));
        cmdSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdSalir.setForeground(new java.awt.Color(255, 255, 255));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel2.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 160, 140));

        setSize(new java.awt.Dimension(474, 219));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdOkActionPerformed
        String nombre, codigo;
        int aux = 0;
        nombre = cmbNombre.getSelectedItem().toString();
        codigo = txtCodigo.getText();
        ArrayList<Mesero> meseros;
        meseros = Helper.traerDatos(rutaM);
        for (int i = 0; i < meseros.size(); i++) {
            if (meseros.get(i).getNombre().equals(nombre) && meseros.get(i).getCodigo().equals(codigo)) {
                JButton botonesA[] = {cmdMesa1, cmdMesa2, cmdMesa3, cmdMesa4, cmdMesa5, cmdMesa6, cmdMesa7, cmdMesa8, cmdMesa9, cmdMesa10};
                Helper.habilitarBotones(botonesA);
                Login_Mesero.this.setVisible(false);
                Principal.jlbIngreso.setText("Mesero");
                aux = 1;
            }
        }
        if (aux == 0) {
            Helper.mensaje(this, "Nombre,Codigo o Contaseña Incorrecto\n"
                    + "Verifique e Intente Nuevamente", 3);
        }
    }//GEN-LAST:event_cmdOkActionPerformed

    private void cmdNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdNuevoActionPerformed
        ArrayList<Administrador> administrador;
        administrador = Helper.traerDatos(rutaA);
        String codigoAdmin = JOptionPane.showInputDialog("Digite El Codigo Del Administrador Para Ingresar Un Mesero");
        for (int i = 0; i < administrador.size(); i++) {
            if (administrador.get(i).getCodigo().equals(codigoAdmin)) {
                Agregar_Mesero a = new Agregar_Mesero(null, true);
                a.setVisible(true);
            } else {
                Helper.mensaje(this, "Codigo Incorrecta", 3);
            }
        }
    }//GEN-LAST:event_cmdNuevoActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        Login_Mesero.this.setVisible(false);
    }//GEN-LAST:event_cmdSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Mesero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login_Mesero dialog = new Login_Mesero(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmbNombre;
    private javax.swing.JButton cmdNuevo;
    private javax.swing.JButton cmdOk;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbCodigo;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
