/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.Pedido;
import static interfaz.Carta.p;
import static interfaz.Principal.*;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author hp 14
 */
public class Opciones extends javax.swing.JDialog {

    /**
     * Creates new form Opciones
     */
    public static String ruta;
    ArrayList<Pedido> pedido;
    public static ObjectOutputStream salida;
    
    public Opciones(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        String ingreso = Principal.jlbIngreso.getText();
        if (ingreso.equals("Administrador")) {
            cmdAbrirCarta.setEnabled(false);
            cmdCancelar.setEnabled(false);
        } else {
        }
        if (ingreso.equals("Mesero")) {
            cmdSaldar.setEnabled(false);
        } else {
        }
        pedido = Helper.traerDatos(ruta);
        try {
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            Logger.getLogger(Opciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        Helper.volcado(salida, pedido);
        Helper.llenarTabla(tblPedido, pedido);
        cmdEliminar.setEnabled(false);
        if (pedido.isEmpty()) {
            cmdSaldar.setEnabled(false);
            cmdCancelar.setEnabled(false);
        } else {
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPedido = new javax.swing.JTable();
        cmdEliminar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        cmdAbrirCarta = new javax.swing.JButton();
        cmdSaldar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        cmdCancelar = new javax.swing.JButton();
        cmdConfirmar = new javax.swing.JButton();
        cmdAggProducto = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OPCIONES DE MESA");
        setIconImage(null);
        setResizable(false);

        jPanel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pedido De Mesa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No°", "Cant", "Producto", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPedido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPedidoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPedido);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 600, 280));

        cmdEliminar.setBackground(new java.awt.Color(0, 0, 0));
        cmdEliminar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdEliminar.setForeground(new java.awt.Color(255, 255, 255));
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 640, 370));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Opciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdAbrirCarta.setBackground(new java.awt.Color(0, 0, 0));
        cmdAbrirCarta.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdAbrirCarta.setForeground(new java.awt.Color(255, 255, 255));
        cmdAbrirCarta.setText("Abrir La Carta");
        cmdAbrirCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAbrirCartaActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAbrirCarta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        cmdSaldar.setBackground(new java.awt.Color(0, 0, 0));
        cmdSaldar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdSaldar.setForeground(new java.awt.Color(255, 255, 255));
        cmdSaldar.setText("Saldar Mesa");
        cmdSaldar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSaldarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSaldar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 230, 120));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCancelar.setBackground(new java.awt.Color(0, 0, 0));
        cmdCancelar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdCancelar.setForeground(new java.awt.Color(255, 255, 255));
        cmdCancelar.setText("Cancelar Mesa");
        cmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        cmdConfirmar.setBackground(new java.awt.Color(0, 0, 0));
        cmdConfirmar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdConfirmar.setForeground(new java.awt.Color(255, 255, 255));
        cmdConfirmar.setText("Confirmar Pedido");
        cmdConfirmar.setEnabled(false);
        cmdConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfirmarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        cmdAggProducto.setBackground(new java.awt.Color(0, 0, 0));
        cmdAggProducto.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdAggProducto.setForeground(new java.awt.Color(255, 255, 255));
        cmdAggProducto.setText("Agregrar Producto");
        cmdAggProducto.setEnabled(false);
        cmdAggProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAggProductoActionPerformed(evt);
            }
        });
        jPanel4.add(cmdAggProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        cmdSalir.setBackground(new java.awt.Color(0, 0, 0));
        cmdSalir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cmdSalir.setForeground(new java.awt.Color(255, 255, 255));
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel4.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 60, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 370, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 566, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAbrirCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAbrirCartaActionPerformed
        Carta a = new Carta(null, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdAbrirCartaActionPerformed

    private void tblPedidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPedidoMouseClicked
        cmdEliminar.setEnabled(true);
    }//GEN-LAST:event_tblPedidoMouseClicked

    private void cmdConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfirmarActionPerformed
        int estado = Integer.parseInt(txtEstado.getText());
        ArrayList<Pedido> p = Helper.traerTabla(tblPedido);
        switch (estado) {
            case 1:
                cmdMesa1.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa1 = "src/datos/pedido_Mesa1.txt";
                ObjectOutputStream salida1;
                try {
                    salida1 = new ObjectOutputStream(new FileOutputStream(rutaMesa1));
                    Helper.guardarArraysList(salida1, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 2:
                cmdMesa2.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa2 = "src/datos/pedido_mesa2.txt";
                ObjectOutputStream salida2;
                try {
                    salida2 = new ObjectOutputStream(new FileOutputStream(rutaMesa2));
                    Helper.guardarArraysList(salida2, p);
                    p.clear();
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                break;
            case 3:
                cmdMesa3.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa3 = "src/datos/pedido_mesa3.txt";
                ObjectOutputStream salida3;
                try {
                    salida3 = new ObjectOutputStream(new FileOutputStream(rutaMesa3));
                    Helper.guardarArraysList(salida3, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 4:
                cmdMesa4.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa4 = "src/datos/pedido_mesa4.txt";
                ObjectOutputStream salida4;
                try {
                    salida4 = new ObjectOutputStream(new FileOutputStream(rutaMesa4));
                    Helper.guardarArraysList(salida4, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 5:
                cmdMesa5.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa5 = "src/datos/pedido_mesa5.txt";
                ObjectOutputStream salida5;
                try {
                    salida5 = new ObjectOutputStream(new FileOutputStream(rutaMesa5));
                    Helper.guardarArraysList(salida5, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 6:
                cmdMesa6.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa6 = "src/datos/pedido_mesa6.txt";
                ObjectOutputStream salida6;
                try {
                    salida6 = new ObjectOutputStream(new FileOutputStream(rutaMesa6));
                    Helper.guardarArraysList(salida6, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 7:
                cmdMesa7.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa7 = "src/datos/pedido_mesa7.txt";
                ObjectOutputStream salida7;
                try {
                    salida7 = new ObjectOutputStream(new FileOutputStream(rutaMesa7));
                    Helper.guardarArraysList(salida7, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 8:
                cmdMesa8.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa8 = "src/datos/pedido_mesa8.txt";
                ObjectOutputStream salida8;
                try {
                    salida8 = new ObjectOutputStream(new FileOutputStream(rutaMesa8));
                    Helper.guardarArraysList(salida8, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 9:
                cmdMesa9.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa9 = "src/datos/pedido_mesa9.txt";
                ObjectOutputStream salida9;
                try {
                    salida9 = new ObjectOutputStream(new FileOutputStream(rutaMesa9));
                    Helper.guardarArraysList(salida9, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
            case 10:
                cmdMesa10.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
                cmdMesa10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
                String rutaMesa10 = "src/datos/pedido_mesa10.txt";
                ObjectOutputStream salida10;
                try {
                    salida10 = new ObjectOutputStream(new FileOutputStream(rutaMesa10));
                    Helper.guardarArraysList(salida10, p);
                } catch (IOException ex) {
                    Logger.getLogger(Carta.class.getName()).log(Level.SEVERE, null, ex);
                }
                Carta.p.clear();
                p.clear();
                break;
        }
        Opciones.this.setVisible(false);
    }//GEN-LAST:event_cmdConfirmarActionPerformed

    private void cmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCancelarActionPerformed
        ArrayList<Pedido> p = Helper.traerTabla(tblPedido);
        p.clear();
        int o = JOptionPane.showConfirmDialog(this, "Si Cancela La Mesa Borrara Todo El Pedido\n"
                + "Desea Continuar??", "CANCELAR MESA", JOptionPane.YES_NO_OPTION);
        if (o == JOptionPane.YES_OPTION) {
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Agregar_Admin.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Agregar_Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcado(salida, p);
            Carta.p.clear();
            Opciones.this.setVisible(false);
            ArrayList<String> p1, p2, p3, p4, p5, p6, p7, p8, p9, p10;
            p1 = Helper.traerDatos("src/datos/Pedido_Mesa1.txt");
            p2 = Helper.traerDatos("src/datos/Pedido_mesa2.txt");
            p3 = Helper.traerDatos("src/datos/Pedido_mesa3.txt");
            p4 = Helper.traerDatos("src/datos/Pedido_mesa4.txt");
            p5 = Helper.traerDatos("src/datos/Pedido_mesa5.txt");
            p6 = Helper.traerDatos("src/datos/Pedido_mesa6.txt");
            p7 = Helper.traerDatos("src/datos/Pedido_mesa7.txt");
            p8 = Helper.traerDatos("src/datos/Pedido_mesa8.txt");
            p9 = Helper.traerDatos("src/datos/Pedido_mesa9.txt");
            p10 = Helper.traerDatos("src/datos/Pedido_mesa10.txt");
            if (p1.isEmpty()) {
                cmdMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p2.isEmpty()) {
                cmdMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p3.isEmpty()) {
                cmdMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p4.isEmpty()) {
                cmdMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p5.isEmpty()) {
                cmdMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p6.isEmpty()) {
                cmdMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p7.isEmpty()) {
                cmdMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p8.isEmpty()) {
                cmdMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p9.isEmpty()) {
                cmdMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
            if (p10.isEmpty()) {
                cmdMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png")));
                cmdMesa10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png")));
            }
        } else {
            
        }
    }//GEN-LAST:event_cmdCancelarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int i, op;
        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar este Producto ?", "Eliminar", JOptionPane.YES_NO_OPTION);
        i = tblPedido.getSelectedRow();
        ArrayList<Pedido> pedido;
        pedido = Helper.traerDatos(ruta);
        try {
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Agregar_Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Agregar_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (p.isEmpty() && op == JOptionPane.YES_OPTION) {
            pedido.remove(i);
            Helper.volcado(salida, pedido);
            Helper.llenarTabla(tblPedido, pedido);
        }
        if (!p.isEmpty() && op == JOptionPane.YES_OPTION) {
            p.remove(i);
            Helper.volcado(salida, p);
            Helper.llenarTabla(tblPedido, p);
        }
        cmdEliminar.setEnabled(false);
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdAggProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAggProductoActionPerformed
        Helper.volcado(salida, p);
        Opciones.this.setVisible(false);
        p.clear();
    }//GEN-LAST:event_cmdAggProductoActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        Opciones.this.setVisible(false);
        p.clear();
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdSaldarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSaldarActionPerformed
        TiqueteVenta a = new TiqueteVenta(null, true);
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cmdSaldarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
            
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opciones.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Opciones dialog = new Opciones(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cmdAbrirCarta;
    public static javax.swing.JButton cmdAggProducto;
    public static javax.swing.JButton cmdCancelar;
    public static javax.swing.JButton cmdConfirmar;
    private javax.swing.JButton cmdEliminar;
    public static javax.swing.JButton cmdSaldar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable tblPedido;
    // End of variables declaration//GEN-END:variables
}
