/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.Mesero;
import static interfaz.Opciones.ruta;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author hp 14
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public static ArrayList<String> p1, p2, p3, p4, p5, p6, p7, p8, p9, p10;

    public Principal() {
        initComponents();
        JButton botonesD[] = {cmdMesa1, cmdMesa2, cmdMesa3, cmdMesa4, cmdMesa5, cmdMesa6, cmdMesa7, cmdMesa8, cmdMesa9, cmdMesa10};
        Helper.deshabilitarBotones(botonesD);
        p1 = Helper.traerDatos("src/datos/Pedido_Mesa1.txt");
        p2 = Helper.traerDatos("src/datos/Pedido_mesa2.txt");
        p3 = Helper.traerDatos("src/datos/Pedido_mesa3.txt");
        p4 = Helper.traerDatos("src/datos/Pedido_mesa4.txt");
        p5 = Helper.traerDatos("src/datos/Pedido_mesa5.txt");
        p6 = Helper.traerDatos("src/datos/Pedido_mesa6.txt");
        p7 = Helper.traerDatos("src/datos/Pedido_mesa7.txt");
        p8 = Helper.traerDatos("src/datos/Pedido_mesa8.txt");
        p9 = Helper.traerDatos("src/datos/Pedido_mesa9.txt");
        p10 = Helper.traerDatos("src/datos/Pedido_mesa10.txt");
        if (!p1.isEmpty()) {
            cmdMesa1.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p2.isEmpty()) {
            cmdMesa2.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p3.isEmpty()) {
            cmdMesa3.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p4.isEmpty()) {
            cmdMesa4.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p5.isEmpty()) {
            cmdMesa5.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p6.isEmpty()) {
            cmdMesa6.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p7.isEmpty()) {
            cmdMesa7.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p8.isEmpty()) {
            cmdMesa8.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p9.isEmpty()) {
            cmdMesa9.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
        if (!p10.isEmpty()) {
            cmdMesa10.setIcon(new ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas.png")));
            cmdMesa10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas_ocupadas_mouse.png")));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlbIngreso = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmdMesa1 = new javax.swing.JButton();
        cmdMesa2 = new javax.swing.JButton();
        cmdMesa3 = new javax.swing.JButton();
        cmdMesa4 = new javax.swing.JButton();
        cmdMesa5 = new javax.swing.JButton();
        cmdMesa6 = new javax.swing.JButton();
        cmdMesa7 = new javax.swing.JButton();
        cmdMesa8 = new javax.swing.JButton();
        cmdMesa9 = new javax.swing.JButton();
        cmdMesa10 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnIngreso = new javax.swing.JMenu();
        mnAdministrador = new javax.swing.JMenuItem();
        mnMesero = new javax.swing.JMenuItem();
        mnOpciones = new javax.swing.JMenu();
        mnReportes = new javax.swing.JMenu();
        mnCantMeseros = new javax.swing.JMenuItem();
        mnAdmin = new javax.swing.JMenuItem();
        mnCantMesasOcupadas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU RESTAURANTE");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbIngreso.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jlbIngreso.setForeground(new java.awt.Color(51, 204, 255));
        jPanel1.add(jlbIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 150, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/bienvenida.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 240));

        cmdMesa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa1.setBorderPainted(false);
        cmdMesa1.setContentAreaFilled(false);
        cmdMesa1.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa1.setFocusable(false);
        cmdMesa1.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa1ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 110));

        cmdMesa2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa2.setBorderPainted(false);
        cmdMesa2.setContentAreaFilled(false);
        cmdMesa2.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa2.setFocusable(false);
        cmdMesa2.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa2ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 140, 110));

        cmdMesa3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa3.setBorderPainted(false);
        cmdMesa3.setContentAreaFilled(false);
        cmdMesa3.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa3.setFocusable(false);
        cmdMesa3.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa3ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 140, 110));

        cmdMesa4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa4.setBorderPainted(false);
        cmdMesa4.setContentAreaFilled(false);
        cmdMesa4.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa4.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa4ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa4, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 140, 110));

        cmdMesa5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa5.setBorderPainted(false);
        cmdMesa5.setContentAreaFilled(false);
        cmdMesa5.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa5.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa5ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 140, 110));

        cmdMesa6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa6.setBorderPainted(false);
        cmdMesa6.setContentAreaFilled(false);
        cmdMesa6.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa6.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa6.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa6ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 390, 140, 110));

        cmdMesa7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa7.setBorderPainted(false);
        cmdMesa7.setContentAreaFilled(false);
        cmdMesa7.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa7.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa7.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa7ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 140, 110));

        cmdMesa8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa8.setBorderPainted(false);
        cmdMesa8.setContentAreaFilled(false);
        cmdMesa8.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa8.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa8.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa8ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 140, 110));

        cmdMesa9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa9.setBorderPainted(false);
        cmdMesa9.setContentAreaFilled(false);
        cmdMesa9.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa9.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa9.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa9ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 140, 110));

        cmdMesa10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles.png"))); // NOI18N
        cmdMesa10.setBorderPainted(false);
        cmdMesa10.setContentAreaFilled(false);
        cmdMesa10.setDisabledIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/No_diponible.png"))); // NOI18N
        cmdMesa10.setPreferredSize(new java.awt.Dimension(147, 110));
        cmdMesa10.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mesas disponibles mouse.png"))); // NOI18N
        cmdMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMesa10ActionPerformed(evt);
            }
        });
        jPanel1.add(cmdMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 540, 140, 110));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Mesa 1");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Mesa 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Mesa 3");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Mesa 4");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Mesa 5");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Mesa 6");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Mesa 7");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Mesa 8");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Mesa 9");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 660, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Mesa 10");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 660, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Mesas Disponibles");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 570, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estados.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Mesas Ocupadas");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 600, -1, -1));

        txtEstado.setText("0");
        txtEstado.setEnabled(false);
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 20, 30));

        mnIngreso.setText("Ingresar ");
        mnIngreso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnAdministrador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnAdministrador.setText("Administrador");
        mnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdministradorActionPerformed(evt);
            }
        });
        mnIngreso.add(mnAdministrador);

        mnMesero.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnMesero.setText("Mesero");
        mnMesero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMeseroActionPerformed(evt);
            }
        });
        mnIngreso.add(mnMesero);

        jMenuBar1.add(mnIngreso);

        mnOpciones.setText("Opciones");
        mnOpciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        mnReportes.setText("Reportes");
        mnReportes.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        mnCantMeseros.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        mnCantMeseros.setText("Cantidad De Meseros ");
        mnCantMeseros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCantMeserosActionPerformed(evt);
            }
        });
        mnReportes.add(mnCantMeseros);

        mnAdmin.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        mnAdmin.setText("Cantidad De Adminstradores");
        mnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAdminActionPerformed(evt);
            }
        });
        mnReportes.add(mnAdmin);

        mnCantMesasOcupadas.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        mnCantMesasOcupadas.setText("Cantidad De Mesas Ocupadas");
        mnCantMesasOcupadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCantMesasOcupadasActionPerformed(evt);
            }
        });
        mnReportes.add(mnCantMesasOcupadas);

        jMenuItem1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jMenuItem1.setText("Cantidad De Mesas Disponibles");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnReportes.add(jMenuItem1);

        mnOpciones.add(mnReportes);

        jMenuBar1.add(mnOpciones);

        mnSalir.setText("Salir");
        mnSalir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(671, 745));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdMesa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa1ActionPerformed
        ruta = "src/datos/Pedido_Mesa1.txt";
        txtEstado.setText("1");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa1ActionPerformed

    private void cmdMesa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa2ActionPerformed
        ruta = "src/datos/Pedido_mesa2.txt";
        txtEstado.setText("2");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa2ActionPerformed

    private void cmdMesa3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa3ActionPerformed
        ruta = "src/datos/Pedido_mesa3.txt";
        txtEstado.setText("3");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa3ActionPerformed

    private void cmdMesa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa4ActionPerformed
        ruta = "src/datos/Pedido_mesa4.txt";
        txtEstado.setText("4");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa4ActionPerformed

    private void cmdMesa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa5ActionPerformed
        ruta = "src/datos/Pedido_mesa5.txt";
        txtEstado.setText("5");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa5ActionPerformed

    private void cmdMesa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa6ActionPerformed
        ruta = "src/datos/Pedido_mesa6.txt";
        txtEstado.setText("6");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa6ActionPerformed

    private void cmdMesa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa7ActionPerformed
        ruta = "src/datos/Pedido_mesa7.txt";
        txtEstado.setText("7");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa7ActionPerformed

    private void cmdMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa8ActionPerformed
        ruta = "src/datos/Pedido_mesa8.txt";
        txtEstado.setText("8");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa8ActionPerformed

    private void cmdMesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa9ActionPerformed
        ruta = "src/datos/Pedido_mesa9.txt";
        txtEstado.setText("9");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa9ActionPerformed

    private void cmdMesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMesa10ActionPerformed
        ruta = "src/datos/Pedido_mesa10.txt";
        txtEstado.setText("10");
        Opciones a = new Opciones(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_cmdMesa10ActionPerformed

    private void mnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_mnSalirMouseClicked

    private void mnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdministradorActionPerformed
        Login_Admin a = new Login_Admin(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnAdministradorActionPerformed

    private void mnMeseroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMeseroActionPerformed
        Login_Mesero a = new Login_Mesero(this, true);
        a.setVisible(true);
    }//GEN-LAST:event_mnMeseroActionPerformed

    private void mnCantMeserosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCantMeserosActionPerformed
        int cont;
        cont = Helper.traerDatos("src/datos/Mesero.txt").size();
        Helper.mensaje(this, "La Cantidad De Meseros ingresados es: " + cont, 1);
    }//GEN-LAST:event_mnCantMeserosActionPerformed

    private void mnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAdminActionPerformed
        int cont;
        cont = Helper.traerDatos("src/datos/Admin.txt").size();
        Helper.mensaje(this, "La Cantidad De Administradores ingresados es: " + cont, 1);
    }//GEN-LAST:event_mnAdminActionPerformed

    private void mnCantMesasOcupadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCantMesasOcupadasActionPerformed
        int ocupadas = 0;
        p1 = Helper.traerDatos("src/datos/Pedido_Mesa1.txt");
        p2 = Helper.traerDatos("src/datos/Pedido_mesa2.txt");
        p3 = Helper.traerDatos("src/datos/Pedido_mesa3.txt");
        p4 = Helper.traerDatos("src/datos/Pedido_mesa4.txt");
        p5 = Helper.traerDatos("src/datos/Pedido_mesa5.txt");
        p6 = Helper.traerDatos("src/datos/Pedido_mesa6.txt");
        p7 = Helper.traerDatos("src/datos/Pedido_mesa7.txt");
        p8 = Helper.traerDatos("src/datos/Pedido_mesa8.txt");
        p9 = Helper.traerDatos("src/datos/Pedido_mesa9.txt");
        p10 = Helper.traerDatos("src/datos/Pedido_mesa10.txt");
        if (!p1.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p2.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p3.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p4.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p5.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p6.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p7.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p8.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p9.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        if (!p10.isEmpty()) {
            ocupadas = ocupadas + 1;
        }
        Helper.mensaje(this, "La Cantidad De Mesas Ocupadas Es " + ocupadas, 1);
    }//GEN-LAST:event_mnCantMesasOcupadasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int disponible = 0;
        p1 = Helper.traerDatos("src/datos/Pedido_Mesa1.txt");
        p2 = Helper.traerDatos("src/datos/Pedido_mesa2.txt");
        p3 = Helper.traerDatos("src/datos/Pedido_mesa3.txt");
        p4 = Helper.traerDatos("src/datos/Pedido_mesa4.txt");
        p5 = Helper.traerDatos("src/datos/Pedido_mesa5.txt");
        p6 = Helper.traerDatos("src/datos/Pedido_mesa6.txt");
        p7 = Helper.traerDatos("src/datos/Pedido_mesa7.txt");
        p8 = Helper.traerDatos("src/datos/Pedido_mesa8.txt");
        p9 = Helper.traerDatos("src/datos/Pedido_mesa9.txt");
        p10 = Helper.traerDatos("src/datos/Pedido_mesa10.txt");
        if (p1.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p2.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p3.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p4.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p5.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p6.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p7.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p8.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p9.isEmpty()) {
            disponible = disponible + 1;
        }
        if (p10.isEmpty()) {
            disponible = disponible + 1;
        }
        Helper.mensaje(this, "La Cantidad De Mesas Ocupadas Es " + disponible, 1);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton cmdMesa1;
    public static javax.swing.JButton cmdMesa10;
    public static javax.swing.JButton cmdMesa2;
    public static javax.swing.JButton cmdMesa3;
    public static javax.swing.JButton cmdMesa4;
    public static javax.swing.JButton cmdMesa5;
    public static javax.swing.JButton cmdMesa6;
    public static javax.swing.JButton cmdMesa7;
    public static javax.swing.JButton cmdMesa8;
    public static javax.swing.JButton cmdMesa9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel jlbIngreso;
    private javax.swing.JMenuItem mnAdmin;
    private javax.swing.JMenuItem mnAdministrador;
    private javax.swing.JMenuItem mnCantMesasOcupadas;
    private javax.swing.JMenuItem mnCantMeseros;
    private javax.swing.JMenu mnIngreso;
    private javax.swing.JMenuItem mnMesero;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenu mnReportes;
    private javax.swing.JMenu mnSalir;
    public static javax.swing.JLabel txtEstado;
    // End of variables declaration//GEN-END:variables
}
